### ISSUE TITLE
Github actions/Google Cloud deployment(4pts)

### ISSUE THREAD

**Issue by Wikitelmex** [IcaliaLabs/rails-app-quickstart#3]
## Background
Github has actions, to automate deployment to google cloud, to its PR, production, or staging environment

## Tasks
- [ ] Configure the Google Cloud project
- [ ] Configure Github actions to automate the deployment (use CG code)
- [ ] Test the deployment in pair programming

**Comment by vovimayhem** [comment]
Closed with #7
