### ISSUE TITLE
Create Assessment tool repo using this template

### ISSUE THREAD

**Issue by Wikitelmex** [IcaliaLabs/rails-app-quickstart#4]
## Background
The assessment tool is the first project where this template will work, we need to start the initial setup of the Assessment tool using this template

## Tasks
- [ ] Use this template to create the Assessment tool repo
- [ ] Configure the Assessment tool repo with the proper databases name, google cloud name, etc.
- [ ] Test everything(deployment, database, specs) to this project
