### ISSUE TITLE
Google Drive Folder

### ISSUE THREAD

**Issue by Wikitelmex** [IcaliaLabs/rails-app-quickstart#5]
## Background
We need to create a GD folder to wrap all the related files to the Assessment tool Project, to avoid asking for documents every time

## Tasks
- [ ] Create GD folder
- [ ] Ask for related files and upload them to the GD folder
- [ ] Invite related people to the folder

**Comment by vovimayhem** [comment]
Not in the template
